config/routes.rb
ThingsIBought::Application.routes.draw do
  resources :purchases
  resources :homers

   root :to => 'purchases#index'

end

app/models/homer.rb
class Homer < ActiveRecord::Base
  attr_accessible :age, :height, :name
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  validates :name, :presence =>  true
  validates :cost, :numericality => { :greater_than =>  0}
  attr_accessible :cost, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/homers_controller.rb
class HomersController < ApplicationController
  # GET /homers
  # GET /homers.json
  def index
    @homers = Homer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @homers }
    end
  end

  # GET /homers/1
  # GET /homers/1.json
  def show
    @homer = Homer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @homer }
    end
  end

  # GET /homers/new
  # GET /homers/new.json
  def new
    @homer = Homer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @homer }
    end
  end

  # GET /homers/1/edit
  def edit
    @homer = Homer.find(params[:id])
  end

  # POST /homers
  # POST /homers.json
  def create
    @homer = Homer.new(params[:homer])

    respond_to do |format|
      if @homer.save
        format.html { redirect_to @homer, notice: 'Homer was successfully created.' }
        format.json { render json: @homer, status: :created, location: @homer }
      else
        format.html { render action: "new" }
        format.json { render json: @homer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /homers/1
  # PUT /homers/1.json
  def update
    @homer = Homer.find(params[:id])

    respond_to do |format|
      if @homer.update_attributes(params[:homer])
        format.html { redirect_to @homer, notice: 'Homer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @homer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homers/1
  # DELETE /homers/1.json
  def destroy
    @homer = Homer.find(params[:id])
    @homer.destroy

    respond_to do |format|
      format.html { redirect_to homers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  # GET /purchases
  # GET /purchases.json
  def index
    @purchases = Purchase.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @purchases }
    end
  end

  # GET /purchases/1
  # GET /purchases/1.json
  def show
    @purchase = Purchase.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @purchase }
    end
  end

  # GET /purchases/new
  # GET /purchases/new.json
  def new
    @purchase = Purchase.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @purchase }
    end
  end

  # GET /purchases/1/edit
  def edit
    @purchase = Purchase.find(params[:id])
  end

  # POST /purchases
  # POST /purchases.json
  def create
    @purchase = Purchase.new(params[:purchase])

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to @purchase, notice: 'Purchase was successfully created.' }
        format.json { render json: @purchase, status: :created, location: @purchase }
      else
        format.html { render action: "new" }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /purchases/1
  # PUT /purchases/1.json
  def update
    @purchase = Purchase.find(params[:id])

    respond_to do |format|
      if @purchase.update_attributes(params[:purchase])
        format.html { redirect_to @purchase, notice: 'Purchase was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy
    @purchase = Purchase.find(params[:id])
    @purchase.destroy

    respond_to do |format|
      format.html { redirect_to purchases_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homers_helper.rb
module HomersHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/homers/_form.html.erb
<%= form_for(@homer) do |f| %>
  <% if @homer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@homer.errors.count, "error") %> prohibited this homer from being saved:</h2>

      <ul>
      <% @homer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homers/edit.html.erb
<h1>Editing homer</h1>

<%= render 'form' %>

<%= link_to 'Show', @homer %> |
<%= link_to 'Back', homers_path %>

app/views/homers/index.html.erb
<h1>Listing homers</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @homers.each do |homer| %>
  <tr>
    <td><%= link_to 'Show', homer %></td>
    <td><%= link_to 'Edit', edit_homer_path(homer) %></td>
    <td><%= link_to 'Destroy', homer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Homer', new_homer_path %>

app/views/homers/new.html.erb
<h1>New homer</h1>

<%= render 'form' %>

<%= link_to 'Back', homers_path %>

app/views/homers/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_homer_path(@homer) %> |
<%= link_to 'Back', homers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThingsIBought</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/purchases/_form.html.erb
<%= form_for(@purchase) do |f| %>
  <% if @purchase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
      <% @purchase.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cost %><br />
    <%= f.text_field :cost %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/purchases/edit.html.erb
<h1>Editing purchase</h1>

<%= render 'form' %>

<%= link_to 'Show', @purchase %> |
<%= link_to 'Back', purchases_path %>

app/views/purchases/index.html.erb
<h1>Listing purchases</h1>

<table>
  <tr>
    <th>Item_ID</th>
    <th>Name</th>
    <th>Cost</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @purchases.each do |purchase| %>
  <tr>
    <td><%= purchase.id %></td>
    <td><%= purchase.name %></td>
    <td><%= purchase.cost %></td>
    <td><%= link_to 'Show', purchase %></td>
    <td><%= link_to 'Edit', edit_purchase_path(purchase) %></td>
    <td><%= link_to 'Destroy', purchase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Purchase', new_purchase_path %>

app/views/purchases/new.html.erb
<h1>New purchase</h1>

<%= render 'form' %>

<%= link_to 'Back', purchases_path %>

app/views/purchases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @purchase.name %>
</p>

<p>
  <b>Cost:</b>
  <%= @purchase.cost %>
</p>


<%= link_to 'Edit', edit_purchase_path(@purchase) %> |
<%= link_to 'Back', purchases_path %>